# Generated by Django 4.2.1 on 2023-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_alter_etudiant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(null=True, upload_to='etudiant_images/'),
        ),
    ]
