# Generated by Django 4.2.1 on 2023-05-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_alter_etudiant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
    ]
