# Generated by Django 4.2.1 on 2023-06-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_remove_etudiant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointageEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pointage', models.DateField(auto_now_add=True)),
                ('heure_pointage', models.TimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.etudiant')),
            ],
        ),
    ]
